### PR TITLE
src/Test.re -> src/Index.re

### PR DESCRIPTION
**Pull request by Aweary**
Looks like rebel expects the default entry point to be Index.re now.

### CODE REVIEW

**Comment by Schmavery** [comment]
It looks like this might be solved by merging #6

**Comment by jordwalke** [comment]
Will merge as soon as the CI passes. It would be awesome if we could trigger the CI when any of the *dependencies* have been updated since the `package.json` just says to pull `rebel` from the `master` branch.

**Comment by jordwalke** [comment]
Thanks!

**Comment by Aweary** [comment]
@jordwalke #6 does include this same change and CI has passed, might as well just merge that one and I'll close this out 😄

**Pull request closed without merging**
